# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/14 11:03:50 by Dugonzal          #+#    #+#              #
#    Updated: 2023/10/20 16:57:36 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:
  nginx:
    container_name: nginx
    #image: hello-world:latest
    # image: nginx:alpine
    build:  
      context: .
      dockerfile:  requirements/nginx/Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 443:443
    networks:
     - inception
networks:
  inception:
    name: inception
