# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/14 11:03:50 by Dugonzal          #+#    #+#              #
#    Updated: 2024/01/11 17:14:49 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mariadb
    env_file: .env
    networks:
      - inception
    restart: always
    expose:
      - 3306/tcp
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - mariadb
    networks:
      - inception
    env_file: .env
    expose:
    - 9000/tcp
    restart: always
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - 443:443/tcp 
    networks:
    - inception
    env_file: .env
    depends_on:
    - wordpress
    volumes_from:
    - wordpress
    #restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/inception/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/inception/data/mariadb
