# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/14 11:03:50 by Dugonzal          #+#    #+#              #
#    Updated: 2023/12/19 14:56:52 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:
  wordpress:
      container_name: wordpress
      build: requirements/wordpress/
      volumes:
       - wordpress:/var/www/html/
      env_file: .env
      ports:
      - 9000:9000
      networks:
       inception:
         ipv4_address: 192.168.1.3
    #restart: always
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - 443:443
    networks:
       inception:
         ipv4_address: 192.168.1.4
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on: 
    - wordpress
    #restart: always
      #
  #  mariadb:
    # container_name: mariadb_test
    #    image: mariadb:11.2
    #   networks:
# inception:
#       ipv4_address: 192.168.1.5
    #   volumes:
# - mariadb:/var/lib/mysql
    #   environment:
# MARIADB_USER: inception
#     MARIADB_PASSWORD: inception
#     MARIADB_DATABASE: inception
#     MARIADB_ROOT_PASSWORD: inception
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
    - mariadb:/var/lib/mysql/
    env_file: .env
    depends_on:
     - wordpress
    networks:
       inception:
          ipv4_address: 192.168.1.5
    #restart: always

networks:
  inception:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 192.168.1.0/24
volumes:
   wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ciclo/Documentos/42/inception/srcs/requirements/wordpress/wordpressVolume/
   mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ciclo/Documentos/42/inception/srcs/requirements/mariadb/mariadbVolume/
