# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/14 11:03:50 by Dugonzal          #+#    #+#              #
#    Updated: 2023/12/19 14:56:52 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:
  wordpress:
      container_name: wordpress
      build:
        context: requirements/wordpress/
        dockerfile:  Dockerfile
      restart: always
      networks:
      - inception
      volumes:
       - wordpress:/var/www/html/wordpress/
      env_file: .env
  nginx:
    container_name: nginx
    build:
      context:  requirements/nginx/
      dockerfile:  Dockerfile
    ports:
      - 443:443
    networks:
     - inception
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on: 
    - wordpress
  mariadb:
      container_name: mariadb
      build:
        context: requirements/mariadb
        dockerfile: Dockerfile
      volumes:
      - mariadb:/var/lib/mysql/
      env_file: .env
      depends_on:
      - wordpress
    # restart: always

networks:
  inception:
    name: inception

volumes:
   wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ciclo/Documentos/42/inception/srcs/requirements/wordpress/wordpressVolume/
   mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ciclo/Documentos/42/inception/srcs/requirements/mariadb/mariadbVolume/
